ALTER TABLE "playlists"
  ADD COLUMN IF NOT EXISTS "layout_mode" TEXT NOT NULL DEFAULT 'zone',
  ADD COLUMN IF NOT EXISTS "grid_rows" INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS "grid_columns" INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS "zones_json" JSONB;
