ALTER TABLE "playlists"
  ADD COLUMN IF NOT EXISTS "display_name" TEXT NOT NULL DEFAULT 'Landscape 16:9',
  ADD COLUMN IF NOT EXISTS "display_width" INTEGER NOT NULL DEFAULT 1920,
  ADD COLUMN IF NOT EXISTS "display_height" INTEGER NOT NULL DEFAULT 1080;
